### ISSUE TITLE
/rc/link data are zero

### ISSUE THREAD

**Issue by cmakelabs** [AndreyTulyakov/ros2_crsf_receiver#2]
Thank you for sharing `crsf_reciever `, after I run the node I echo the topic `/rc/channels` I seem to get reasonable output, however when I echo `/rc/link`  all data I get are zeros:

```
ros2 topic echo /rc/channels

---
ch1: 0
ch2: 0
ch3: 0
ch4: 0
ch5: 1537
ch6: 0
ch7: 2262
ch8: 0
ch9: 0
ch10: 0
ch11: 0
ch12: 0
ch13: 19173
ch14: 0
ch15: 0
ch16: 0


```

however

```
ros2 topic echo /rc/link

uplink_rssi_ant1:
  data: 0
uplink_rssi_ant2:
  data: 0
uplink_status:
  data: 0
uplink_snr:
  data: 0
active_antenna:
  data: 0
rf_mode:
  data: 0
uplink_tx_power:
  data: 0
downlink_rssi:
  data: 0
downlink_status:
  data: 0
downlink_snr:
  data: 0

```

Would be really grateful if you could tell why this is happening, I have double checked my port and tried different baudrate, checked the wiring and everything seems correct, yet I am still not able to get any data.
